name: gunshop
description: 'A new Flutter project.'
publish_to: 'none' # Prevents publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^5.0.0
  intl: ^0.18.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/images/logo.png'

flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/product1.png
    - assets/images/product2.png
    - assets/images/product3.png
    - assets/images/product4.png
    - assets/images/product5.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/font/Poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/font/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/font/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/font/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/font/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/font/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/font/Poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/font/Poppins/Poppins-Black.ttf
          weight: 900
