name: gunshop
description: 'A new Flutter project.'
publish_to: 'none' # Prevents publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^5.0.0
  intl: ^0.18.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/images/logo.png'

flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/default_avatar.png
    - assets/images/products/tactical_combat_knife.jpg
    - assets/images/products/military_grenade_dummy.jpg
    - assets/images/products/tactical_backpack_45L.jpg
    - assets/images/products/glock_19 _pistol.jpg
    - assets/images/products/9mm_dummy_ammo.jpg
    - assets/images/products/tactical_gloves.jpg
    - assets/images/products/mp5_submachine_gun.jpg
    - assets/images/products/tactical_helmet.jpg
    - assets/images/products/full_face.jpg
    - assets/images/products/tactical_plate.jpg
    - assets/images/products/assault_rifle.jpg
    - assets/images/products/tactical_kit.jpg
    - assets/images/banner.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/font/Poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/font/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/font/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/font/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/font/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/font/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/font/Poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/font/Poppins/Poppins-Black.ttf
          weight: 900
